### ISSUE TITLE
Documentation request: Maven pull

### ISSUE THREAD

**Issue by ehx-v1** [bjornharrtell/jts2geojson#11]
Hi, my problems in #9 and #10 are now solved. However, it took me a little while to figure out that I need an extra repository, and that I have to pull version 0.7.0, which is the latest release, instead of version 0.8.0, which is the version in the Master branch POM.

While this is probably due to the fact that I'm not very proficient with Maven, there may be other unexperienced users stumbling upon this problem. That's why I think corner cases like these should be documented.

**Comment by bjornharrtell** [comment]
It's published on maven central. You don't need an extra repository, what makes you think that?

The released versions are tagged. Master branch is for development. This is common practice.

Please try to refrain from opening issues until you have put more time into making sure there is an issue at all.

**Comment by ehx-v1** [comment]
Your POM looked like it defines an external repository where the project is deployed. Thus the impression.

As for the version, it's also common practice to instantly make the Master branch version available as a snapshot. If you don't do that, it should be documented somewhere. Just saying.

**Comment by bjornharrtell** [comment]
I understand your position and sorry for sounding harsh. It's unlikely that I'll find time to improve this project in the short term but pull requests are welcome.
