### ISSUE TITLE
Put properties to JSON

### ISSUE THREAD

**Issue by nevyen** [bjornharrtell/jts2geojson#18]
Hey, I'm using your libaray to convert my geometry objects into geoJson. 

But I need to add additional info to the geojson objects. Such as a name, an ID and a number value. 
Is this possible? 

Or is it possible to convert an object of mine which is containing a Geometry value to geojson ?

**Comment by bjornharrtell** [comment]
Yes you need to construct and convert Feature objects. It's clearly demonstrated at https://github.com/bjornharrtell/jts2geojson.
