### ISSUE TITLE
Feature object does not include the "id" field

### ISSUE THREAD

**Issue by wbendick** [bjornharrtell/jts2geojson#2]
If a feature has a commonly used identifier, that identifier should be included as a member of the feature object with the name "id".

http://geojson.org/geojson-spec.html#feature-objects

**Comment by noahtaylor** [comment]
I agree with with @wbendick, I had the same issue actually.  I was going to commit a fix to the library but got too busy.  As a short term workaround I just extended the Feature and added an Id field, really though the feature class should be updated.

**Comment by bjornharrtell** [comment]
Makes sense. Implemented in latest release. Please get back to me if it does not work as expected.
