### ISSUE TITLE
Support JTS version 1.15.0

### ISSUE THREAD

**Issue by dalbani** [bjornharrtell/jts2geojson#25]
A couple of years after version 1.14.0 was released, version 1.15.0 is now available: https://github.com/locationtech/jts/releases/tag/jts-1.15.0.
It includes a change of the Maven artifact and group ID, as well as the Java package names: https://github.com/locationtech/jts/blob/master/MIGRATION.md.
A changelog is also available: https://github.com/locationtech/jts/commit/9bf21460fe0016d097fc928b0991e99ee10a5c52#diff-3e58566997a9f59b19d4a3bcc830d85a.

Would you consider upgrading to this new version?

**Comment by bjornharrtell** [comment]
I will consider doing it when possible.

I'm wondering though if not https://github.com/locationtech/jts/tree/master/modules/io/common/src/main/java/org/locationtech/jts/io/geojson can replace this project.
