### ISSUE TITLE
Provide method to allow user to specify the GeometryFactory

### ISSUE THREAD

**Issue by fbl100** [bjornharrtell/jts2geojson#28]
Provide the user a mechanism to specify the GeometryFactory used in the GeoJSONReader.  An example use case for this would be a geometry factory that creates Polygons that properly calculate their area on the surface of the earth.

**Comment by fbl100** [comment]
FWIW I have a local branch with this working.  Not sure if I need special permissions to push my branch for considerations.

**Comment by patzi** [comment]
Hi, I'd like to work on this as I need the possibility to set the `GeometryFactory#SRID` . Is see tow possible ways to achieve this:
- change the api of `GeoJSONReader`, make the factory a setable property and call `read(...)` like this:
`GeoJSONReader.instance().read(...)`, where `GeoJSONReader.instance()` returns a static instance of a `GeoJSONReader` that would be in the same state as the current version.
Or:
`GeoJSONReader reader = new GeoJSONReader();
reader.read(...);`
- change `read(...)` to `read(..., GeometryFactory aFactory)` and use the existing `GeoJSONReader.factory` when the argument `aFactory` is `null`. Additional I would add `read(...)` as a shorthand for `read(..., null)`

What would you prefer @bjornharrtell ? Second would be of course with lot less changes to current users. I could then provide a pull request. A similar approach could also be used for #22

**Comment by bjornharrtell** [comment]
Second option looks pragmatic to me. I found the initial description of this issue hard to understand which is the reason for the lack of response.

**Comment by patzi** [comment]
OK, then I will make a pull request for this with the second option.
