### ISSUE TITLE
Downgrade jdk version to 1.7

### ISSUE THREAD

**Issue by gorshkov-leonid** [bjornharrtell/jts2geojson#30]
Hello, a lot of customers use jdk 1.7. So we also have to choose libraries that compiled for jdk 7 or publish downgraded fork. I think there isn't reason to use jdk 1.7 in this project, because it was builded successfully with options 1.7 in maven-compiler-plugin. 
Could you downgrade version of java source/target in maven compiler plugin or release special version for us? It will be better then for with changed coordinates.

**Comment by bjornharrtell** [comment]
Not interested in supporting JDK 1.7.

**Comment by gorshkov-leonid** [comment]
Ок

**Comment by gorshkov-leonid** [comment]
How many problems did you encounter due to the class version change?

**Comment by bjornharrtell** [comment]
I don't have any problems. :)

**Comment by gorshkov-leonid** [comment]
I predicted that answer) sorry for bother :) 
But I thought if a library uses required dependencies instead of latest ones then it can be used by more people. So, jts2geojson can use java 1.7 and jackson 2.7.x. If you don't want ... Well, there is no way. Thank you for answer

**Comment by gorshkov-leonid** [comment]
Got it, thank you.
