### ISSUE TITLE
Null properties Jackson serializer - change null collection to empty one

### ISSUE THREAD

**Issue by mrisney** [bjornharrtell/jts2geojson#31]
Running into an issue when using  Geotools, GeoDataFactory. When parsing the GeoJSON, if no properties are present, getting a null instead of an empty pair of brackets. Is there a way the properties map could be configured so that  properties : {} could be output instead of properties:null ?

Jackson 2.9 adds new properties to existing (but rarely used) @JsonSetter annotation to allow specifying one of common alternatives.

propose that org.wololo.geojson.Feature use the @JsonSetter annotation :

	@JsonSetter(nulls = Nulls.AS_EMPTY)
	public Map<String, Object> getProperties() {
		return properties;
	}

**Comment by bjornharrtell** [comment]
I'm not sure I want to change from null to {} by default. From the spec it's clear that null is valid. What is the issue you are having with GeoTools?

**Comment by mrisney** [comment]
org.geotools.data.geojson.GeoJSONDataStore bombs out when trying to pass in a GeoJSON with properties:null. Workaround is  

GeoJSONWriter writer = new GeoJSONWriter(); 
GeoJSON geoJSONObj = writer.write(features);
String geoJSONStr = geoJSONObj.toString().replaceAll("null", "{}");

This is ugly.

**Comment by bjornharrtell** [comment]
To me, this seems like an issue with GeoTools.

**Comment by mrisney** [comment]
Mapbox
https://github.com/mapbox/tippecanoe/issues/15
