### ISSUE TITLE
Release with 1.8 compatibility

### ISSUE THREAD

**Issue by willcohen** [bjornharrtell/jts2geojson#34]
0.14.1 appears to have been compiled with JDK11: see [here](https://travis-ci.org/Factual/geo/jobs/568943166#L600) for a downstream error when trying to use the library under JDK8. The pom has [1.8](https://github.com/bjornharrtell/jts2geojson/blob/master/pom.xml#L86) set as target and source, so I'm not sure what needs to be changed in the deploy process for this.

**Comment by bjornharrtell** [comment]
Ah yes you are right and that was unintentional. I've compiled with JDK8 and released as 0.14.2 (will take a while to reach Maven Central). To get JDK8 compat with JDK11 there have been some changes I think, but I have no time to investigate that now.

**Comment by willcohen** [comment]
Thanks so much, @bjornharrtell!
