### ISSUE TITLE
Support JTS 1.17

### ISSUE THREAD

**Issue by jiayuasu** [bjornharrtell/jts2geojson#40]
If use jts2geojson together with JTS 1.17+, the following exception will occur:

java.lang.NoSuchMethodError: org.locationtech.jts.geom.Polygon.getExteriorRing()Lorg/locationtech/jts/geom/LineString;
	at org.wololo.jts2geojson.GeoJSONWriter.convert(GeoJSONWriter.java:79)
	at org.wololo.jts2geojson.GeoJSONWriter.write(GeoJSONWriter.java:28)

Can you please support JTS 1.17+?

**Comment by jiayuasu** [comment]
According to JTS 1.17 release notes: https://github.com/locationtech/jts/releases

This is due to an API change:

## API Changes
### Change Polygon getExteriorRing and getInteriorRingN accessors to return LinearRing.
* This is a binary incompatible change to the method signature. Recompilation is necessary. No source code changes are required.

**Comment by lockwobr** [comment]
Version 1.18 is out now... any updates on this? if its so simple, and i open a pr for it would get merged?

**Comment by jiayuasu** [comment]
@lockwobr Yes, I also need this package to support 1.18 :-)

**Comment by lockwobr** [comment]
just opened a pr to fix this issue.

https://github.com/bjornharrtell/jts2geojson/pull/41
