### ISSUE TITLE
CRS support

### ISSUE THREAD

**Issue by mplatt** [bjornharrtell/jts2geojson#7]
Is there any support for [named CRS](http://geojson.org/geojson-spec.html#named-crs) planned? Specifically, I would love to use something along the lines of [org.geolatte.common.dataformats.json.jackson.GeoJsonDeserializer](https://github.com/GeoLatte/geolatte-common/blob/master/src/main/java/org/geolatte/common/dataformats/json/jackson/GeoJsonDeserializer.java) to translate the CRS into an SRID for jts. Do you feel this kind of functionality would make any sense in this package?

**Comment by bjornharrtell** [comment]
Makes sense. No plans. :)

**Comment by mplatt** [comment]
Cool stuff, thanks for the info. I might prepare a PR then

**Comment by ngocketit** [comment]
Hi. What's the status of this @mplatt ?

**Comment by bjornharrtell** [comment]
I would say it is safe to assume interest wasn't that great after all as it was more than 5 years ago this was closed with no follow up.   😉

**Comment by mplatt** [comment]
Yea, sorry guys. I have to admit I don't even understand my own request
anymore 😃

**Comment by ngocketit** [comment]
@bjornharrtell Yes I sort of agree since it's not a hard requirement for me to have named CRS supported. Basically what I did is to assume the geometry that comes from the geojson is with the targeted SRID and use ST_SetSrid after ST_GeomFromGeoJSON. With CRS in geojson, I can omit ST_SetSrid.
