### ISSUE TITLE
Conflicting property-based creators

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/jts2geojson#8]
I'm getting the following problem when trying to deserialise:

com.fasterxml.jackson.databind.JsonMappingException: Conflicting property-based creators: already had explicitly marked [constructor for org.wololo.geojson.LineString,

I suspect the introduction of multiple JsonCreator constructors.

**Comment by bjornharrtell** [comment]
The multiple JsonCreator was introduced with #6.

**Comment by jeffreyeriksondg** [comment]
I've taken the liberty of submitting a pull request with a fix for this: #12 

Please let me know if you'd like any more info or have any comments on the PR.  Thanks!

**Comment by bjornharrtell** [comment]
Thanks for the fix, #12 is now merged.
