### ISSUE TITLE
Cannot access via Maven

### ISSUE THREAD

**Issue by ehx-v1** [bjornharrtell/jts2geojson#9]
When I put the artifact from the pom.xml in my project pom.xml, it says "Missing artifact". Either the library is not on Maven Central (while the setup implies it were), or the upload is broken.

It shouldn't be my Maven because it loads other libraries (which, besides from Apache Commons from Glassfish, are Neo4j and Neo4j Spatial with all their nested dependencies) without any problems.

**Comment by bjornharrtell** [comment]
Should work. If you can provide something more substantial to support that it does not please reopen.
